packages:
  - "packages/page"
  - "packages/pm-basic-setup"
  - "packages/pm-e2e-helper"
  - "packages/pm-img"
  - "packages/pm-link"
  - "packages/pm-react"
  - "packages/pm-utils"
  - "packages/utils"
  - "tools/json-format"
