packages:
  - "packages/page"
  - "packages/pm-basic-setup"
  - "packages/pm-component-placeholder"
  - "packages/pm-e2e-helper"
  - "packages/pm-mark-link"
  - "packages/pm-node-image"
  - "packages/pm-react"
  - "packages/pm-test-helper"
  - "packages/pm-utils"
  - "packages/utils"
  - "tools/json-format"
